spring.application.name=Job_Application_Tracker

spring.datasource.url=jdbc:mysql://localhost:3306/job_tracker?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=YOUR_MYSQL_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

gemini.api.key=YOUR_GEMINI_API_KEY